### ISSUE TITLE
Cannot access admin page

### ISSUE THREAD

**Issue by treldor** [nickjj/build-a-saas-app-with-flask#33]
Hi Nick
I make some change and now can't access admin dashboard
dev@localhost.com/password is incorrect
where is admin username/password defined?

Thank you

**Comment by nickjj** [comment]
https://github.com/nickjj/build-a-saas-app-with-flask/blob/master/catwatch/lib/db_seed.py#L18

It will use `SEED_ADMIN_EMAIL` which is `dev@localhost.com` unless you changed it in `config/settings.py`. It also uses `password` as the password.

If it's not working then the database hasn't been seeded yet. Part of running `db reset` includes seeding it, which is all documented here https://github.com/nickjj/build-a-saas-app-with-flask#initialize-everything-and-view-the-app.

**Comment by treldor** [comment]
ahh OK perfect found it
thank you so much nickjj
