### ISSUE TITLE
Adding Custom CSS and JS

### ISSUE THREAD

**Issue by eliehamouche** [nickjj/build-a-saas-app-with-flask#35]
What's the best way on adding custom .css and .js files,
I added my files into assets, but they don't seem to be in effect.

**Comment by nickjj** [comment]
When adding new files you would have to restart the webpack dev server.

**Comment by eliehamouche** [comment]
So if I add a .js file into catwatch/assets/scripts, Its contents should be available in all templates after restarting & rebuilding assets correct?

Also where is the javascript called? I can't find any javascript in any of the jinja2 templates.

**Comment by nickjj** [comment]
It's bundled into a single file and included at the footer of the layout:
https://github.com/nickjj/build-a-saas-app-with-flask/blob/master/catwatch/templates/layouts/base.jinja2#L43

All of the JS is in here:
https://github.com/nickjj/build-a-saas-app-with-flask/tree/master/catwatch/assets/scripts

All of it is handled through webpack here:
https://github.com/nickjj/build-a-saas-app-with-flask/blob/master/config/webpack.config.js

**Comment by eliehamouche** [comment]
I added custom CSS and JS files.
The css has taken effect, but the JS file doesn't seem to have an effect. 
I don't think it's being used by webpack. Do I have to import it or register it anywhere?

**Comment by nickjj** [comment]
What does the JS do?

You'd have to add it to this list:
https://github.com/nickjj/build-a-saas-app-with-flask/blob/master/config/webpack.config.js#L54-L56

**Comment by eliehamouche** [comment]
Just the JS file for Bootstrap Switch: http://www.bootstrap-switch.org/
If I load the script manually it works fine in the browser.

I've done the following in webpack.config.js:

`  app_js: [
    'bootstrap-switch',
    path.join(contextRoot, assets.scripts.path, 'entry.js')
  ],`

But that doesn't seem correct.

**Comment by nickjj** [comment]
Oh, it's a vendor JS.

In that case, add it here:
https://github.com/nickjj/build-a-saas-app-with-flask/blob/master/config/webpack.config.js#L60-L62

Then add it to your package.json since it's on npm:
https://www.npmjs.com/package/bootstrap-switch

npm install it and then add this code `$("[name='my-checkbox']").bootstrapSwitch();` to the `entry.js`, or break it out into its own file and only use it on the page(s) you want.

**Comment by treldor** [comment]
That did it! Thanks Nick.

**Comment by treldor** [comment]
wrong three

**Comment by eliehamouche** [comment]
??
Adding to Vendor worked. Closed.
