### ISSUE TITLE
SMTPAuthenticationError 534

### ISSUE THREAD

**Issue by fergvick** [nickjj/build-a-saas-app-with-flask#36]
When trying to send an email through the smtp.gmail.com server I receive a notification saying that the app doesn't meet modern security standards. 

What can I add the bring Catwatch up to these standards so I can safely use the Gmail SMTP server?

**Comment by nickjj** [comment]
Which app is giving you that notification?

If you use gmail as your mail server, it comes pre-configured to send mail with TLS enabled.

You might get that warning if you try to send mail to a recipient whose mail server does not support TLS, in which case this isn't a limitation of catwatch or gmail.

**Comment by fergvick** [comment]
This is when I try to send an email from the Catwatch flask app (issue contact email, forget password email)

**Comment by nickjj** [comment]
The Flask-Mail extension (the package powering e-mail in catch) doesn't support OAuth 2 which is the only transport method that would allow you to run it without enabling "less secure apps".

https://security.googleblog.com/2014/04/new-security-measures-will-affect-older.html

@miguelgrinberg has a good write up here explaining why: https://github.com/miguelgrinberg/flasky/issues/65#issuecomment-135903296

**Comment by fergvick** [comment]
This clarifies things, thanks
