### ISSUE TITLE
Getting a ImportError when running with docker compose

### ISSUE THREAD

**Issue by probably-correct** [nickjj/build-a-saas-app-with-flask#37]
Getting a  ImportError: No module named snakeeyes.blueprints.contact when trying to use it with docker. I have not changed any code. Just pulled the code and ran it as in the document. 

Let me know if you have any idea how to solve this.

**Comment by nickjj** [comment]
Hey, it's been a week without any feedback. Feel free to re-open this or comment on whether or not the above worked.
