### ISSUE TITLE
gunicorn does not run on windows

### ISSUE THREAD

**Issue by Code4SAFrankie** [nickjj/build-a-saas-app-with-flask#39]
`gunicorn` does not run on Windows 10 and I can't install `docker` because I only have Windows 10 Home Edition and `docker` requires Windows 10 Pro. So I'm trying to use `waitress` instead of `gunicorn`. Do you know what the equivalent command would be to:

gunicorn -b 0.0.0.0:8000 --access-logfile - "snakeeyes.app:create_app()"

for `waitress`?

I'm also not sure from which directory I am supposed to be running this command from.

**Comment by nickjj** [comment]
Hi,

You can install Docker on Windows 10 Home using Docker Toolbox from https://docs.docker.com/toolbox/. Over a thousand people who are taking the course are using that set up successfully.

**Comment by Code4SAFrankie** [comment]
Got it working with `waitress-serve.exe --listen=*:8000 --call snakeeyes.app:create_app`
